# Generated by Django 4.1.5 on 2023-01-07 16:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('appeals', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(blank=True)),
                ('file', models.FileField(blank=True, upload_to='Answers/files/')),
                ('answer_type', models.CharField(choices=[('done', 'bajarildi'), ('rejected', 'rad etildi')], max_length=10)),
                ('answer_address', models.CharField(choices=[('site', 'Sayt'), ('email', 'Email'), ('site_and_email', 'Sayt va Email')], max_length=15)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('updated_date', models.DateTimeField(auto_now=True)),
                ('active', models.CharField(choices=[('send', 'Yuborilsin'), ('save', "Saqlab qo'yilsin")], max_length=4)),
                ('appeal', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='get_answers', to='appeals.appeal')),
                ('author', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
