# Generated by Django 4.1.5 on 2023-01-12 03:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('appeals', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(blank=True)),
                ('file', models.FileField(blank=True, null=True, upload_to='Answers/files/')),
                ('answer_type', models.CharField(choices=[('d', 'bajarildi'), ('r', 'rad etildi')], max_length=1)),
                ('answer_address', models.CharField(choices=[('s', 'Sayt'), ('e', 'Email'), ('se', 'Sayt va Email')], max_length=2)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_updated', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('appeal', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='appeals.appeal')),
                ('author', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
