# Generated by Django 4.1.5 on 2023-01-07 18:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('appeals', '0004_rename_created_date_appeal_date_created_and_more'),
        ('answers', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='answer',
            old_name='created_date',
            new_name='date_created',
        ),
        migrations.RenameField(
            model_name='answer',
            old_name='updated_date',
            new_name='date_updated',
        ),
        migrations.RemoveField(
            model_name='answer',
            name='active',
        ),
        migrations.AddField(
            model_name='answer',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='answer',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='answer',
            name='answer_address',
            field=models.CharField(choices=[('s', 'Sayt'), ('e', 'Email'), ('se', 'Sayt va Email')], max_length=2),
        ),
        migrations.AlterField(
            model_name='answer',
            name='answer_type',
            field=models.CharField(choices=[('d', 'bajarildi'), ('r', 'rad etildi')], max_length=1),
        ),
        migrations.AlterField(
            model_name='answer',
            name='appeal',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='appeals.appeal'),
        ),
        migrations.AlterField(
            model_name='answer',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='Answers/files/'),
        ),
    ]
