# Generated by Django 4.1.5 on 2023-01-12 03:51

import ckeditor.fields
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EduSocial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('link', models.URLField()),
                ('logo', models.ImageField(upload_to='Applicants_panel/Social_images/')),
            ],
        ),
        migrations.CreateModel(
            name='ApplicantsTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('university_name', models.CharField(max_length=50)),
                ('background', models.ImageField(upload_to='Applicants_panel/images/')),
                ('logo', models.ImageField(blank=True, null=True, upload_to='Applicants_panel/images/')),
                ('back_logo', models.ImageField(blank=True, null=True, upload_to='Applicants_panel/images/')),
                ('title', models.CharField(max_length=50)),
                ('sup_title', models.CharField(max_length=100)),
                ('accept_text', ckeditor.fields.RichTextField(blank=True)),
                ('main_site_link', models.URLField()),
                ('tel', models.CharField(blank=True, max_length=13)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('step_title_1', models.CharField(max_length=50)),
                ('step_title_2', models.CharField(max_length=50)),
                ('step_title_3', models.CharField(max_length=50)),
                ('aside_title', models.CharField(max_length=20)),
                ('answer_title', models.CharField(max_length=30)),
                ('statistics_title', models.CharField(max_length=30)),
                ('rector_name', models.CharField(max_length=100)),
                ('rector_avatar', models.ImageField(upload_to='Applicants_panel/images/')),
                ('rector_position', models.CharField(blank=True, max_length=100)),
                ('rector_reception_time', models.CharField(blank=True, max_length=50)),
                ('updated_date', models.DateField(auto_now=True)),
                ('author', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
