# Generated by Django 4.1.5 on 2023-01-07 17:05

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('general', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Applicants_panel',
            new_name='ApplicantsTemplate',
        ),
        migrations.RenameModel(
            old_name='Social',
            new_name='EduSocial',
        ),
    ]
