# Generated by Django 4.0.3 on 2022-04-13 09:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import phonenumber_field.modelfields
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Appeal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('appeal_subject', models.CharField(max_length=100)),
                ('appeal_text', models.TextField()),
                ('appeal_file', models.FileField(blank=True, upload_to='Appeal Files/')),
                ('appeal_type', models.CharField(choices=[('Ariza', 'Ariza'), ('Shikoyat', 'Shikoyat'), ('Taklif', 'Taklif'), ('boshqa', 'boshqa')], max_length=10)),
                ('appeal_direction', models.CharField(choices=[('Diplom olish masalalari', 'Diplom olish masalalari'), ('Ishga joylash, ishdagi tortishuv, oylik maoshi', 'Ishga joylash, ishdagi tortishuv, oylik maoshi'), ("Kontrakt to'lovi to'g'risida", "Kontrakt to'lovi to'g'risida"), ('Magistratura masalalari', 'Magistratura masalalari'), ("Fuqarolar murojaatlari to'g'risida", "Fuqarolar murojaatlari to'g'risida"), ('Moliyaviy masalalar', 'Moliyaviy masalalar'), ('Talaba ustidan shikoyat', 'Talaba ustidan shikoyat'), ('Rahbar faoliyatidan norozilik arizasi', 'Rahbar faoliyatidan norozilik arizasi'), ('Stipendiya masalalari', 'Stipendiya masalalari'), ("O'qishga kirish to'g'risida", "O'qishga kirish to'g'risida"), ("O'qishni ko'chirish to'g'risida", "O'qishni ko'chirish to'g'risida"), ("O'qishni tiklash to'g'risida", "O'qishni tiklash to'g'risida"), ("Ijodiy imtihondan norozilik to'g'risida", "Ijodiy imtihondan norozilik to'g'risida"), ("Diplom xaqqoniyligini tasdiqlab berish to'g'risida", "Diplom xaqqoniyligini tasdiqlab berish to'g'risida"), ('Nafaqa masalalari', 'Nafaqa masalalari'), ("Arxiv ma'lumotlarini olish to'grisida", "Arxiv ma'lumotlarini olish to'grisida"), ('Ikkinchi mutaxasislik', 'Ikkinchi mutaxasislik'), ('Kitob nashr qilish', 'Kitob nashr qilish'), ('Ixtiro qilish taklifi', 'Ixtiro qilish taklifi'), ('Taklif va minnatdorchilik', 'Taklif va minnatdorchilik'), ("Sirtqi o'qish masalalari", "Sirtqi o'qish masalalari"), ("Yotoqxona masalalari bo'yicha", "Yotoqxona masalalari bo'yicha"), ("Olimpiada masalasi bo'yicha", "Olimpiada masalasi bo'yicha"), ("Boshqa yo'nalishlar", "Boshqa yo'nalishlar")], max_length=70)),
                ('privacy', models.BooleanField(default=False)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('code', models.UUIDField(default=uuid.uuid4)),
                ('applicant_name', models.CharField(max_length=40)),
                ('applicant_tel_num', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None)),
                ('applicant_email', models.EmailField(blank=True, max_length=254)),
                ('applicant_province', models.CharField(choices=[('Toshkent', 'Toshkent'), ('Samarqand', 'Samarqand'), ('Andijon', 'Andijon'), ('Fargona', 'Fargona'), ('Namangan', 'Namangan'), ('Qashqadaryo', 'Qashqadaryo'), ('Surxondaryo', 'Surxondaryo'), ('Buxoro', 'Buxoro'), ('Navoiy', 'Navoiy'), ('Xorazm', 'Xorazm'), ('Sirdaryo', 'Sirdaryo'), ('Jizzax', 'Jizzax'), ("Qoraqalpog'iston Respublikasi", "Qoraqalpog'iston Respublikasi")], max_length=40)),
                ('applicant_type', models.CharField(choices=[('Yuridik_shaxs', 'Yuridik shaxs'), ('Jismoniy_shaxs', 'Jismoniy shaxs')], max_length=15)),
                ('applicant_position', models.CharField(choices=[('Talaba', 'Talaba'), ('Ota ona', 'Ota ona'), ('Universitet xodimi', 'Universitet xodimi'), ('Tashkilot', 'Tashkilot'), ('Boshqa', 'Boshqa')], max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Social',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('link', models.URLField()),
                ('logo', models.ImageField(upload_to='Applicants panel/Social images/')),
            ],
        ),
        migrations.CreateModel(
            name='Applicants_panel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('background', models.ImageField(upload_to='Applicants panel/images/')),
                ('logo', models.ImageField(blank=True, upload_to='Applicants panel/images/')),
                ('back_logo', models.ImageField(blank=True, upload_to='Applicants panel/images/')),
                ('title', models.CharField(max_length=50)),
                ('tel', phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, region=None)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('step_title_1', models.CharField(max_length=50)),
                ('step_title_2', models.CharField(max_length=50)),
                ('step_title_3', models.CharField(max_length=50)),
                ('rector_name', models.CharField(max_length=100)),
                ('rector_avatar', models.ImageField(upload_to='Applicants panel/images/')),
                ('rector_position', models.CharField(blank=True, max_length=100)),
                ('rector_reception_time', models.CharField(blank=True, max_length=50)),
                ('updated_date', models.DateField(auto_now=True)),
                ('author', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('file', models.FileField(blank=True, upload_to='Answers/files/')),
                ('answer_type', models.CharField(choices=[('done', 'bajarildi'), ('rejected', 'rad etildi')], max_length=10)),
                ('answer_address', models.CharField(choices=[('site', 'Sayt'), ('email', 'Email'), ('site_and_email', 'Sayt va Email')], max_length=15)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('updated_date', models.DateTimeField(auto_now=True)),
                ('active', models.CharField(choices=[('send', 'Yuborilsin'), ('save', "Saqlab qo'yilsin")], max_length=4)),
                ('appeal', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='appeals.appeal')),
                ('author', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
