# Generated by Django 4.0.3 on 2022-04-15 11:08

import ckeditor.fields
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import phonenumber_field.modelfields
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Appeal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('appeal_subject', models.CharField(max_length=60)),
                ('appeal_text', models.TextField()),
                ('appeal_file', models.FileField(blank=True, upload_to='Appeal_Files/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'txt', 'doc', 'docx', 'ppt'])])),
                ('appeal_type', models.CharField(choices=[('ariza', 'Ariza'), ('shikoyat', 'Shikoyat'), ('taklif', 'Taklif'), ('boshqa', 'boshqa')], max_length=10)),
                ('appeal_direction', models.CharField(choices=[('diplom_olish', 'Diplom olish masalalari'), ('ishga_joylash', 'Ishga joylash, ishdagi tortishuv, oylik maoshi'), ('kontrakt_tolovi', "Kontrakt to'lovi to'g'risida"), ('mag_masalalari', 'Magistratura masalalari'), ('fuqarolar_murojaatlari', "Fuqarolar murojaatlari to'g'risida"), ('moliyaviy_masalalar', 'Moliyaviy masalalar'), ('talaba_ustidan', 'Talaba ustidan shikoyat'), ('rahbar_faoliyatidan', 'Rahbar faoliyatidan norozilik arizasi'), ('stipendiya_masalalari', 'Stipendiya masalalari'), ('oqishga_kirish', "O'qishga kirish to'g'risida"), ('oqishni_kochirish', "O'qishni ko'chirish to'g'risida"), ('oqishni_tiklash', "O'qishni tiklash to'g'risida"), ('ijodiy_imtihondan', "Ijodiy imtihondan norozilik to'g'risida"), ('diplom_xaqqoniyligini', "Diplom xaqqoniyligini tasdiqlab berish to'g'risida"), ('nafaqa_masalalari', 'Nafaqa masalalari'), ('arxiv_malumotlarini', "Arxiv ma'lumotlarini olish to'grisida"), ('ikkinchi_mutaxasislik', 'Ikkinchi mutaxasislik'), ('kitob_nashr', 'Kitob nashr qilish'), ('ixtiro_qilish', 'Ixtiro qilish taklifi'), ('taklif_va', 'Taklif va minnatdorchilik'), ('sirtqi_oqish', "Sirtqi o'qish masalalari"), ('yotoqxona_masalalari', "Yotoqxona masalalari bo'yicha"), ('olimpiada_masalasi', "Olimpiada masalasi bo'yicha"), ('boshqa_yo', "Boshqa yo'nalishlar")], max_length=70)),
                ('privacy', models.BooleanField(default=False)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('code', models.UUIDField(default=uuid.uuid4)),
                ('appeal_status', models.CharField(choices=[('new', 'Yangi'), ('process', "Ko'rib chiqilmoqda"), ('rejected', 'Rad etilgan'), ('completed', 'Bajarilgan')], default='new', max_length=10)),
                ('applicant_name', models.CharField(max_length=40)),
                ('applicant_tel_num', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None)),
                ('applicant_email', models.EmailField(blank=True, max_length=254)),
                ('applicant_province', models.CharField(choices=[('toshkent', 'Toshkent'), ('samarqand', 'Samarqand'), ('andijon', 'Andijon'), ('fargona', 'Fargona'), ('namangan', 'Namangan'), ('qashqadaryo', 'Qashqadaryo'), ('surxondaryo', 'Surxondaryo'), ('buxoro', 'Buxoro'), ('navoiy', 'Navoiy'), ('xorazm', 'Xorazm'), ('sirdaryo', 'Sirdaryo'), ('jizzax', 'Jizzax'), ('qoraqalpoq', "Qoraqalpog'iston Respublikasi")], max_length=40)),
                ('applicant_type', models.CharField(choices=[('yuridik_shaxs', 'Yuridik shaxs'), ('jismoniy_shaxs', 'Jismoniy shaxs')], max_length=15)),
                ('applicant_position', models.CharField(choices=[('talaba', 'Talaba'), ('ota_ona', 'Ota ona'), ('universitet_xodimi', 'Universitet xodimi'), ('tashkilot', 'Tashkilot'), ('boshqa', 'Boshqa')], max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Social',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('link', models.URLField()),
                ('logo', models.ImageField(upload_to='Applicants_panel/Social_images/')),
            ],
        ),
        migrations.CreateModel(
            name='Applicants_panel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('university_name', models.CharField(max_length=50)),
                ('background', models.ImageField(upload_to='Applicants_panel/images/')),
                ('logo', models.ImageField(blank=True, upload_to='Applicants_panel/images/')),
                ('back_logo', models.ImageField(blank=True, upload_to='Applicants_panel/images/')),
                ('title', models.CharField(max_length=50)),
                ('sup_title', models.CharField(max_length=100)),
                ('accept_text', ckeditor.fields.RichTextField(blank=True)),
                ('main_site_link', models.URLField()),
                ('tel', phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, region=None)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('step_title_1', models.CharField(max_length=50)),
                ('step_title_2', models.CharField(max_length=50)),
                ('step_title_3', models.CharField(max_length=50)),
                ('aside_title', models.CharField(max_length=20)),
                ('answer_title', models.CharField(max_length=30)),
                ('statistics_title', models.CharField(max_length=30)),
                ('rector_name', models.CharField(max_length=100)),
                ('rector_avatar', models.ImageField(upload_to='Applicants_panel/images/')),
                ('rector_position', models.CharField(blank=True, max_length=100)),
                ('rector_reception_time', models.CharField(blank=True, max_length=50)),
                ('updated_date', models.DateField(auto_now=True)),
                ('author', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('file', models.FileField(blank=True, upload_to='Answers/files/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'txt', 'doc', 'docx', 'ppt'])])),
                ('answer_type', models.CharField(choices=[('done', 'bajarildi'), ('rejected', 'rad etildi')], max_length=10)),
                ('answer_address', models.CharField(choices=[('site', 'Sayt'), ('email', 'Email'), ('site_and_email', 'Sayt va Email')], max_length=15)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('updated_date', models.DateTimeField(auto_now=True)),
                ('active', models.CharField(choices=[('send', 'Yuborilsin'), ('save', "Saqlab qo'yilsin")], max_length=4)),
                ('appeal', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='appeals.appeal')),
                ('author', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
