# Generated by Django 4.1.5 on 2023-01-12 03:51

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AppealDirection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('direction', models.CharField(max_length=200, unique=True)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('creator', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Appeal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('appeal_subject', models.CharField(blank=True, max_length=60)),
                ('appeal_text', models.TextField(blank=True)),
                ('appeal_file', models.FileField(blank=True, null=True, upload_to='Appeal_Files/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'txt', 'doc', 'docx', 'ppt', 'xlsx', 'xls'])])),
                ('appeal_type', models.CharField(choices=[('a', 'Ariza'), ('s', 'Shikoyat'), ('t', 'Taklif'), ('b', 'boshqa')], max_length=1)),
                ('privacy', models.BooleanField(default=False)),
                ('code', models.UUIDField(default=uuid.uuid4)),
                ('appeal_status', models.CharField(choices=[('n', 'Yangi'), ('p', "Ko'rib chiqilmoqda"), ('r', 'Rad etilgan'), ('d', 'Bajarilgan')], default='n', max_length=1)),
                ('applicant_full_name', models.CharField(max_length=40)),
                ('applicant_tel_num', models.CharField(max_length=13)),
                ('applicant_email', models.EmailField(blank=True, max_length=254, null=True)),
                ('applicant_province', models.CharField(choices=[('tas', 'Toshkent'), ('sam', 'Samarqand'), ('an', 'Andijon'), ('far', 'Fargona'), ('nam', 'Namangan'), ('qash', 'Qashqadaryo'), ('sur', 'Surxondaryo'), ('bux', 'Buxoro'), ('nav', 'Navoiy'), ('xor', 'Xorazm'), ('sir', 'Sirdaryo'), ('jiz', 'Jizzax'), ('qor', "Qoraqalpog'iston Respublikasi")], max_length=4)),
                ('applicant_type', models.CharField(choices=[('y', 'Yuridik shaxs'), ('j', 'Jismoniy shaxs')], max_length=1)),
                ('applicant_position', models.CharField(choices=[('tal', 'Talaba'), ('oon', 'Ota ona'), ('oqi', "O'qituvchi"), ('uni', 'Universitet xodimi'), ('tas', 'Tashkilot'), ('bos', 'Boshqa')], max_length=3)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_updated', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('appeal_direction', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='appeals.appealdirection')),
            ],
        ),
    ]
