# Generated by Django 4.1.5 on 2023-01-07 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appeals', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appeal',
            name='appeal_direction',
            field=models.CharField(choices=[('dip', 'Diplom olish masalalari'), ('ish', 'Ishga joylash, ishdagi tortishuv, oylik maoshi'), ('kon', "Kontrakt to'lovi to'g'risida"), ('mag', 'Magistratura masalalari'), ('fuq', "Fuqarolar murojaatlari to'g'risida"), ('mol', 'Moliyaviy masalalar'), ('tal', 'Talaba ustidan shikoyat'), ('rah', 'Rahbar faoliyatidan norozilik arizasi'), ('sti', 'Stipendiya masalalari'), ('oqk', "O'qishga kirish to'g'risida"), ('oqc', "O'qishni ko'chirish to'g'risida"), ('oqt', "O'qishni tiklash to'g'risida"), ('ijo', "Ijodiy imtihondan norozilik to'g'risida"), ('dix', "Diplom xaqqoniyligini tasdiqlab berish to'g'risida"), ('naf', 'Nafaqa masalalari'), ('arx', "Arxiv ma'lumotlarini olish to'grisida"), ('ikk', 'Ikkinchi mutaxasislik'), ('kit', 'Kitob nashr qilish'), ('ixt', 'Ixtiro qilish taklifi'), ('tak', 'Taklif va minnatdorchilik'), ('sir', "Sirtqi o'qish masalalari"), ('yot', "Yotoqxona masalalari bo'yicha"), ('oli', "Olimpiada masalasi bo'yicha"), ('bos', "Boshqa yo'nalishlar")], max_length=3),
        ),
        migrations.AlterField(
            model_name='appeal',
            name='appeal_status',
            field=models.CharField(choices=[('n', 'Yangi'), ('p', "Ko'rib chiqilmoqda"), ('r', 'Rad etilgan'), ('d', 'Bajarilgan')], default='n', max_length=1),
        ),
        migrations.AlterField(
            model_name='appeal',
            name='appeal_type',
            field=models.CharField(choices=[('a', 'Ariza'), ('s', 'Shikoyat'), ('t', 'Taklif'), ('b', 'boshqa')], max_length=10),
        ),
        migrations.AlterField(
            model_name='appeal',
            name='applicant_position',
            field=models.CharField(choices=[('tal', 'Talaba'), ('oon', 'Ota ona'), ('oqi', "O'qituvchi"), ('uni', 'Universitet xodimi'), ('tas', 'Tashkilot'), ('bos', 'Boshqa')], max_length=3),
        ),
        migrations.AlterField(
            model_name='appeal',
            name='applicant_province',
            field=models.CharField(choices=[('tas', 'Toshkent'), ('sam', 'Samarqand'), ('an', 'Andijon'), ('far', 'Fargona'), ('nam', 'Namangan'), ('qash', 'Qashqadaryo'), ('sur', 'Surxondaryo'), ('bux', 'Buxoro'), ('nav', 'Navoiy'), ('xor', 'Xorazm'), ('sir', 'Sirdaryo'), ('jiz', 'Jizzax'), ('qor', "Qoraqalpog'iston Respublikasi")], max_length=4),
        ),
        migrations.AlterField(
            model_name='appeal',
            name='applicant_type',
            field=models.CharField(choices=[('y', 'Yuridik shaxs'), ('j', 'Jismoniy shaxs')], max_length=1),
        ),
    ]
