# Generated by Django 4.0.3 on 2022-04-20 13:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('appeals', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answer',
            name='appeal',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='get_answers', to='appeals.appeal'),
        ),
        migrations.AlterField(
            model_name='appeal',
            name='applicant_position',
            field=models.CharField(choices=[('talaba', 'Talaba'), ('ota_ona', 'Ota ona'), ('oqituvchi', "O'qituvchi"), ('universitet_xodimi', 'Universitet xodimi'), ('tashkilot', 'Tashkilot'), ('boshqa', 'Boshqa')], max_length=20),
        ),
    ]
