# Generated by Django 4.1.5 on 2023-01-07 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appeals', '0002_alter_appeal_appeal_direction_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appeal',
            name='applicant_type',
            field=models.CharField(choices=[('a', 'Ariza'), ('s', 'Shikoyat'), ('t', 'Taklif'), ('b', 'boshqa')], max_length=1),
        ),
    ]
