# Generated by Django 4.0.3 on 2022-04-13 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appeals', '0002_alter_appeal_appeal_subject'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appeal',
            name='appeal_file',
            field=models.FileField(blank=True, upload_to='Appeal_Files/'),
        ),
        migrations.AlterField(
            model_name='appeal',
            name='appeal_subject',
            field=models.CharField(max_length=60),
        ),
    ]
