# Generated by Django 4.0.3 on 2022-05-21 07:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appeals', '0002_alter_appeal_applicant_tel_num'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applicants_panel',
            name='tel',
            field=models.CharField(blank=True, max_length=13),
        ),
    ]
