# Generated by Django 4.0.3 on 2022-05-04 08:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appeals', '0003_alter_answer_text'),
    ]

    operations = [
        migrations.RenameField(
            model_name='answer',
            old_name='file',
            new_name='answer_file',
        ),
    ]
