# Generated by Django 4.1.5 on 2023-01-07 18:32

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appeals', '0003_alter_appeal_applicant_type'),
    ]

    operations = [
        migrations.RenameField(
            model_name='appeal',
            old_name='created_date',
            new_name='date_created',
        ),
        migrations.AddField(
            model_name='appeal',
            name='date_updated',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='appeal',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='appeal',
            name='appeal_file',
            field=models.FileField(blank=True, null=True, upload_to='Appeal_Files/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'txt', 'doc', 'docx', 'ppt', 'xlsx', 'xls'])]),
        ),
        migrations.AlterField(
            model_name='appeal',
            name='applicant_email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='appeal',
            name='applicant_type',
            field=models.CharField(choices=[('y', 'Yuridik shaxs'), ('j', 'Jismoniy shaxs')], max_length=1),
        ),
    ]
