# Generated by Django 4.1.5 on 2023-01-07 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appeals', '0004_rename_created_date_appeal_date_created_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='appeal',
            old_name='applicant_name',
            new_name='applicant_full_name',
        ),
        migrations.AlterField(
            model_name='appeal',
            name='appeal_type',
            field=models.CharField(choices=[('a', 'Ariza'), ('s', 'Shikoyat'), ('t', 'Taklif'), ('b', 'boshqa')], max_length=1),
        ),
    ]
