# Generated by Django 4.0.3 on 2022-04-13 10:34

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appeals', '0004_alter_appeal_appeal_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appeal',
            name='appeal_file',
            field=models.FileField(blank=True, upload_to='Appeal Files/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf'])]),
        ),
    ]
