# Generated by Django 4.0.3 on 2022-05-04 08:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appeals', '0004_rename_file_answer_answer_file'),
    ]

    operations = [
        migrations.RenameField(
            model_name='answer',
            old_name='answer_file',
            new_name='file',
        ),
    ]
