# Generated by Django 4.0.3 on 2022-05-04 09:16

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appeals', '0005_rename_answer_file_answer_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appeal',
            name='appeal_file',
            field=models.FileField(blank=True, upload_to='Appeal_Files/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'txt', 'doc', 'docx', 'ppt', 'xlsx', 'xls'])]),
        ),
    ]
