# Generated by Django 4.0.3 on 2022-05-04 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appeals', '0006_alter_appeal_appeal_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appeal',
            name='appeal_status',
            field=models.CharField(choices=[('new', 'Yangi'), ('process', "Ko'rib chiqilmoqda"), ('rejected', 'Rad etilgan'), ('done', 'Bajarilgan')], default='new', max_length=10),
        ),
    ]
