# Generated by Django 4.0.3 on 2022-05-04 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appeals', '0007_alter_appeal_appeal_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appeal',
            name='appeal_subject',
            field=models.CharField(blank=True, max_length=60),
        ),
        migrations.AlterField(
            model_name='appeal',
            name='appeal_text',
            field=models.TextField(blank=True),
        ),
    ]
